name: node
type: nodejs

web:
  commands:
    start: "PM2_HOME=/app/run pm2 start index.js --no-daemon"
  locations:
    "/":
      passthru: true
      expires: 1h
      root: "public"
dependencies:
  nodejs:
    pm2: "^0.15.10"
relationships:
  mongodb: "mongodb:mongodb"
mounts:
  "/run": "shared:files/run"
disk: 512